import { existsSync, readdirSync } from "node:fs";
import { join } from "node:path";

/**
 * Rendered previews of each preset.
 *
 * Generated by `node scripts/make-style-previews.mjs`, which runs every preset's
 * own style block through the same model the product uses. That matters: a
 * preview has to be a truthful sample of what the preset produces, which rules
 * out stock or scraped images — those would be someone else's work presented as
 * ours, and they would not match what a customer actually gets.
 *
 * Every preview renders the same scene, so the picker is a direct comparison:
 * one subject, twelve treatments.
 */

const DIR = join(process.cwd(), "public", "style-previews");
const IMAGE = /\.(jpe?g|png|webp)$/i;

let cache: Record<string, string> | null = null;

function index(): Record<string, string> {
  if (cache) return cache;

  const found: Record<string, string> = {};
  if (existsSync(DIR)) {
    try {
      for (const file of readdirSync(DIR)) {
        if (!IMAGE.test(file)) continue;
        found[file.replace(IMAGE, "")] = `/style-previews/${file}`;
      }
    } catch {
      // Fall through to swatches.
    }
  }

  cache = found;
  return found;
}

export function getStylePreview(styleId: string): string | null {
  return index()[styleId] ?? null;
}

export function stylePreviews(): Record<string, string> {
  return index();
}
