import Link from "next/link";
import { Mark } from "@/components/Wordmark";
import { SUPPORT_EMAIL } from "@/lib/config";

export default function Footer() {
  return (
    <footer className="mt-24 border-t border-[var(--line)] bg-[var(--paper-sunk)]">
      <div className="mx-auto max-w-6xl px-6 py-14">
        <div className="flex flex-col gap-10 md:flex-row md:justify-between">
          <div className="max-w-xs">
            <Mark size={26} />
            <p className="mt-4 text-[14px] leading-relaxed text-[var(--ink-muted)]">
              A full set of style-consistent images for your video, from the
              script you already wrote.
            </p>
          </div>

          <div className="flex gap-14 text-[14px]">
            <div>
              <div className="eyebrow mb-3">Product</div>
              <ul className="space-y-2 text-[var(--ink-muted)]">
                <li><Link className="hover:text-[var(--ink)]" href="/#how">How it works</Link></li>
                <li><Link className="hover:text-[var(--ink)]" href="/#styles">Styles</Link></li>
                <li><Link className="hover:text-[var(--ink)]" href="/#pricing">Pricing</Link></li>
                <li><Link className="hover:text-[var(--ink)]" href="/#faq">FAQ</Link></li>
              </ul>
            </div>
            <div>
              <div className="eyebrow mb-3">Company</div>
              <ul className="space-y-2 text-[var(--ink-muted)]">
                <li>
                  <Link className="hover:text-[var(--ink)]" href="/terms">
                    Terms
                  </Link>
                </li>
                <li>
                  <Link className="hover:text-[var(--ink)]" href="/privacy">
                    Privacy
                  </Link>
                </li>
                <li>
                  <a className="hover:text-[var(--ink)]" href={`mailto:${SUPPORT_EMAIL}`}>
                    Support
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>

        <div className="mt-12 flex flex-col gap-2 border-t border-[var(--line)] pt-6 text-[13px] text-[var(--ink-faint)] sm:flex-row sm:justify-between">
          <span>© {new Date().getFullYear()} Cutframe</span>
          <span>Images are generated by AI. You own what you make.</span>
        </div>
      </div>
    </footer>
  );
}
